"use strict";

const assert = require("assert");
const lib = require("../scripts/meta-loop-control-lib.cjs");
const packet = { id: "run-1", objective: "test" };
let ledger = lib.newLedger(packet, { capacity: 2, expiresAt: "2099-01-01T00:00:00.000Z" });
assert.deepStrictEqual(lib.validatePacket(packet), { valid: true, errors: [] });
assert.strictEqual(lib.validatePacket({}).valid, false);
lib.claim(ledger, "a");
assert.throws(() => lib.claim(ledger, "a"), /duplicate/i);
lib.confirmSpawn(ledger, "a", "att-a");
lib.claim(ledger, "b");
assert.throws(() => lib.claim(ledger, "c"), /capacity/i);
lib.cancel(ledger, "b");
lib.claim(ledger, "c");
assert.throws(() => lib.confirmSpawn(ledger, "c", "att-a"), /already been recorded/i);
lib.confirmSpawn(ledger, "c", "att-c");
assert.throws(() => lib.recordReturn(ledger, "c", "wrong", "x"), /does not match/i);
lib.recordReturn(ledger, "a", "att-a", "one");
lib.recordReturn(ledger, "c", "att-c", "two");
assert.throws(() => lib.recordReturn(ledger, "c", "att-c", "replay"), /not awaiting/i);
lib.synthesize(ledger);
assert.throws(() => lib.claim(ledger, "post-synthesis"), /after synthesis/i);
lib.finish(ledger);
assert.strictEqual(ledger.state, "finished");
const expired = lib.newLedger(packet, { expiresAt: "2026-01-02T00:00:00.000Z" });
lib.claim(expired, "x", { now: "2026-01-01T00:00:00.000Z" });
lib.reconcileLedger(expired, { now: "2026-01-03T00:00:00.000Z" });
assert.strictEqual(expired.state, "expired");
const expiryEvents = expired.events.filter((item) => item.type === "expired").length;
lib.reconcileLedger(expired, { now: "2026-01-04T00:00:00.000Z" });
assert.strictEqual(expired.events.filter((item) => item.type === "expired").length, expiryEvents);
assert.throws(() => lib.assertLedger({}), /legacy/i);
assert.throws(() => lib.assertLedger({ ...ledger, unknown: true }), /invalid|legacy/i);
assert.throws(() => lib.assertLedger({ ...ledger, workers: { bad: { status: "returned" } } }), /invalid|legacy/i);
const malformedEvent = JSON.parse(JSON.stringify(ledger)); malformedEvent.events[0].extra = true;
assert.throws(() => lib.assertLedger(malformedEvent), /invalid|legacy/i);
const incompleteEvent = JSON.parse(JSON.stringify(ledger)); delete incompleteEvent.events[0].detail;
assert.throws(() => lib.assertLedger(incompleteEvent), /invalid|legacy/i);
const activeAfterSynthesis = lib.newLedger(packet, { expiresAt: "2099-01-01T00:00:00.000Z" });
lib.claim(activeAfterSynthesis, "active"); activeAfterSynthesis.synthesis = { at: "2026-01-01T00:00:00.000Z", returns: [] };
assert.throws(() => lib.finish(activeAfterSynthesis), /nonterminal/i);
process.stdout.write("meta-loop-control unit tests passed\n");
